[package]
name = "udr_python"
version = "0.1.0"
edition = "2021"

[lib]
name = "udr"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }
udr_core = { path = "../udr_core" }
